"""
Auto Report Generator — produces IWMP-format monitoring reports.

Reproduces the exact structure of existing IWMP district summary reports:
  1. Study area + micro-watershed count
  2. Satellite & ancillary data section (auto-filled)
  3. Site-wise change section with NDVI/NDWI/LULC tables
  4. Validation appendix (corroborated vs. flagged changes)
  5. WII ranking table

Output: DOCX (via python-docx) → WeasyPrint → PDF
"""
from __future__ import annotations

import io
from dataclasses import dataclass
from typing import List

from docx import Document
from docx.shared import Pt, RGBColor, Cm, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement


@dataclass
class EpochRow:
    """One row in the site-wise change table."""
    watershed_code: str
    watershed_name: str
    epoch_from: str
    epoch_to: str
    delta_ndvi: float
    delta_water_ha: float
    delta_degraded_ha: float
    wii_score: float
    band: str
    photo_confidence: float
    flagged_mismatches: int
    validation_status: str  # PHOTO_CORROBORATED | UNVERIFIED | FLAGGED_MISMATCH


@dataclass
class ReportData:
    """Complete data bundle for report generation. No IO — passed from the service layer."""
    district_name: str
    district_code: str
    state_name: str
    epoch_from: str
    epoch_to: str
    epoch_from_date: str    # e.g., "April 2023"
    epoch_to_date: str      # e.g., "March 2024"
    total_micro_watersheds: int
    total_area_ha: float
    sensor: str             # e.g., "Sentinel-2 MSI (10m resampled to 30m)"
    resolution_m: int
    rows: List[EpochRow]
    avg_wii: float
    flagged_mismatches_total: int
    generated_by: str
    generated_at: str       # ISO datetime string


def _set_cell_bg(cell, hex_color: str) -> None:
    """Set background color of a DOCX table cell."""
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    tcPr.append(shd)


def _band_color(band: str) -> str:
    """Return DOCX hex color for WII band."""
    return {
        "EXCELLENT": "C8F7C5",
        "GOOD": "EBF7C5",
        "MODERATE": "FFF8C5",
        "POOR": "FFE8C5",
        "CRITICAL": "FFC5C5",
    }.get(band, "FFFFFF")


def generate_docx(data: ReportData) -> bytes:
    """
    Generate an IWMP-format monitoring report as DOCX bytes.
    Pure function: returns bytes, accepts no database connections.
    """
    doc = Document()

    # ── Page setup ────────────────────────────────────────────────────────────
    section = doc.sections[0]
    section.page_width = Cm(21)
    section.page_height = Cm(29.7)
    section.left_margin = Cm(2.5)
    section.right_margin = Cm(2.0)
    section.top_margin = Cm(2.5)
    section.bottom_margin = Cm(2.0)

    # ── Title ─────────────────────────────────────────────────────────────────
    doc.add_heading(
        "INTEGRATED WATERSHED MANAGEMENT PROGRAMME (IWMP)", level=1
    ).alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_heading(
        f"Monitoring Report — {data.district_name} District, {data.state_name}",
        level=2,
    ).alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_heading(
        f"Epoch {data.epoch_from} ({data.epoch_from_date}) → "
        f"Epoch {data.epoch_to} ({data.epoch_to_date})",
        level=3,
    ).alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph(
        f"Auto-generated by the Watershed Intelligence Platform  |  "
        f"Generated by: {data.generated_by}  |  {data.generated_at}"
    ).paragraph_format.space_before = Pt(6)

    doc.add_paragraph()

    # ── Section 1: Study Area ────────────────────────────────────────────────
    doc.add_heading("1. Study Area", level=2)
    para = doc.add_paragraph()
    para.add_run(f"District: ").bold = True
    para.add_run(f"{data.district_name} ({data.district_code}), {data.state_name}\n")
    para.add_run("Total Micro-Watersheds: ").bold = True
    para.add_run(f"{data.total_micro_watersheds}\n")
    para.add_run("Total Area: ").bold = True
    para.add_run(f"{data.total_area_ha:,.1f} ha\n")
    para.add_run("Programme: ").bold = True
    para.add_run("WDC-PMKSY 2.0 / IWMP — Department of Land Resources, MoRD\n")

    # ── Section 2: Satellite & Ancillary Data ────────────────────────────────
    doc.add_heading("2. Satellite & Ancillary Data", level=2)
    sat_table = doc.add_table(rows=5, cols=2)
    sat_table.style = "Table Grid"
    rows_data = [
        ("Sensor", data.sensor),
        ("Spatial Resolution", f"{data.resolution_m} m"),
        ("Indices Computed", "NDVI, NDWI, LULC (Random Forest classification)"),
        ("Epoch Period", f"{data.epoch_from_date} to {data.epoch_to_date}"),
        ("Validation Source", "DRISHTI geo-tagged field photos (auto-classified by CV model)"),
    ]
    for r_idx, (label, value) in enumerate(rows_data):
        sat_table.rows[r_idx].cells[0].text = label
        sat_table.rows[r_idx].cells[0].paragraphs[0].runs[0].bold = True
        sat_table.rows[r_idx].cells[1].text = value

    doc.add_paragraph()

    # ── Section 3: Site-Wise Change Table ────────────────────────────────────
    doc.add_heading("3. Site-Wise Change Summary", level=2)
    doc.add_paragraph(
        f"The table below summarises satellite-derived land/water change for all "
        f"{data.total_micro_watersheds} micro-watersheds, cross-validated against "
        f"field photos collected through DRISHTI."
    )

    change_table = doc.add_table(rows=1, cols=8)
    change_table.style = "Table Grid"
    headers = [
        "Watershed Code", "Name", "ΔNDVI",
        "ΔWater (ha)", "ΔDegraded (ha)",
        "WII Score", "Band", "Validation Status",
    ]
    hdr_cells = change_table.rows[0].cells
    for i, h in enumerate(headers):
        hdr_cells[i].text = h
        hdr_cells[i].paragraphs[0].runs[0].bold = True
        _set_cell_bg(hdr_cells[i], "2E75B6")
        # White text on dark header
        run = hdr_cells[i].paragraphs[0].runs[0]
        run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
        run.font.size = Pt(8)

    for row in data.rows:
        r_cells = change_table.add_row().cells
        r_cells[0].text = row.watershed_code
        r_cells[1].text = row.watershed_name or "—"
        r_cells[2].text = f"{row.delta_ndvi:+.3f}"
        r_cells[3].text = f"{row.delta_water_ha:+.1f}"
        r_cells[4].text = f"{row.delta_degraded_ha:+.1f}"
        r_cells[5].text = f"{row.wii_score:.1f}"
        r_cells[6].text = row.band
        r_cells[7].text = row.validation_status.replace("_", " ")
        # Colour WII band cell
        _set_cell_bg(r_cells[5], _band_color(row.band))
        _set_cell_bg(r_cells[6], _band_color(row.band))
        # Flag mismatches in red
        if row.flagged_mismatches > 0:
            _set_cell_bg(r_cells[7], "FFC5C5")
        for cell in r_cells:
            for para in cell.paragraphs:
                for run in para.runs:
                    run.font.size = Pt(8)

    doc.add_paragraph()

    # ── Section 4: Validation Appendix ───────────────────────────────────────
    doc.add_heading("4. Validation Appendix", level=2)
    doc.add_paragraph(
        "This section identifies which satellite-claimed changes were corroborated "
        "by ground photos, which remain unverified, and which require field verification."
    )

    corroborated = sum(1 for r in data.rows if r.validation_status == "PHOTO_CORROBORATED")
    unverified = sum(1 for r in data.rows if r.validation_status == "UNVERIFIED")
    flagged = sum(1 for r in data.rows if r.validation_status == "FLAGGED_MISMATCH")

    val_table = doc.add_table(rows=4, cols=3)
    val_table.style = "Table Grid"
    val_headers = [["Status", "Count", "Action Required"]]
    val_data = [
        ["Photo Corroborated", str(corroborated), "None — approved for scoring"],
        ["Unverified (no photos)", str(unverified), "Field verification recommended"],
        ["Flagged Mismatch", str(flagged), "⚠ Field verification required"],
    ]
    for r_idx, (label, count, action) in enumerate(val_data):
        cells = val_table.rows[r_idx].cells
        cells[0].text = label
        cells[1].text = count
        cells[2].text = action
        if label == "Flagged Mismatch":
            _set_cell_bg(cells[0], "FFC5C5")
            _set_cell_bg(cells[1], "FFC5C5")
            _set_cell_bg(cells[2], "FFC5C5")

    doc.add_paragraph()

    # ── Section 5: WII Summary ────────────────────────────────────────────────
    doc.add_heading("5. Watershed Impact Index Summary", level=2)
    doc.add_paragraph(
        f"Average WII for {data.district_name} district: "
        f"{data.avg_wii:.1f}/100  |  "
        f"Total flagged mismatches requiring field verification: {data.flagged_mismatches_total}"
    )
    doc.add_paragraph(
        "WII formula:  WII = 0.30 × ΔNDVI_norm + 0.30 × ΔWaterSpread_norm "
        "+ 0.25 × (1 − ΔDegradedLand_norm) + 0.15 × PhotoValidationConfidence"
    ).paragraph_format.space_before = Pt(6)

    # ── Footer disclaimer ─────────────────────────────────────────────────────
    doc.add_paragraph()
    disclaimer = doc.add_paragraph(
        "DISCLAIMER: This report is auto-generated by an AI-assisted system. "
        "All satellite-derived figures are based on Sentinel-2 imagery and are "
        "approximate (±10%). Changes flagged as 'Requires Field Verification' must "
        "be verified by a qualified field officer before administrative action. "
        "Satellite correlation does not imply causation."
    )
    disclaimer.paragraph_format.space_before = Pt(6)
    for run in disclaimer.runs:
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    # Serialize to bytes
    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()
